モデルテスト(日報、ユーザー)とシステムテスト(日報)を作成
doitumura/fjord-books_app pull request #13
Opened 2022-12-20 01:23 UTC by doitumura

2022-12-25 15:38 UTC, u1tnk requested changes

2022-12-25 15:38 UTC, u1tnk commented on test/models/report_test.rb
> +    assert_equal('2022-01-01'.to_date, @report.created_on)
これだと現在の日付を返すというテストにならないので、 fixturesの日付指定をやめて、現在の日付と比較しましょう。

2022-12-25 15:38 UTC, u1tnk commented on test/models/user_test.rb
> +    assert(@user2.following?(@user1))
テスト内容敵には問題無いのですが、fixturesで関連を定義してしまうと、 fixturesで定義したユーザがこのテスト専用になってしまいます。
テスト専用のデータはテスト内/beforeなどで作ると良いでしょう。また、`following?`がfalseを返すケースもテストしましょう。

2022-12-25 15:38 UTC, u1tnk commented on test/models/user_test.rb
> +    assert(@user1.followed_by?(@user2))
`following?`と同様です。

2022-12-25 15:38 UTC, u1tnk commented on test/models/user_test.rb
> +    assert_equal('one@example.com', @user1.name_or_email)
こちらもテスト内でこのテスト用のデータを準備した方が分かりやすいですね。

2022-12-26 01:29 UTC, u1tnk requested changes
ERBLintの自動修正差分が多くて、理由を確認したところ、
どうもforkしたタイミングから更新されておらず、元のfjord-books_appでは修正されている問題が反映されていないようです。

https://github.com/doitumura/fjord-books_app/compare/09-testing...fjordllc:fjord-books_app:09-testing

doitumura/fjord-books_app/compare/09-testing と この my-testingにfjordllcリポジトリの修正を取り込んでください。

2022-12-26 03:01 UTC, u1tnk commented
> doitumura/fjord-books_app/compare/09-testing と この my-testingにfjordllcリポジトリの修正を取り込んでください。

こちら難しそうならご相談ください 🙏

2022-12-26 04:11 UTC, doitumura commented
> doitumura/fjord-books_app/compare/09-testing と この my-testingにfjordllcリポジトリの修正を取り込んでください。

以下の手順で取り込もうと考えているのですが問題ないでしょうか？

1. upstreamにhttps://github.com/fjordllc/fjord-books_app.gitを登録
2. upstreamから最新のリポジトリをfetch
3. ローカルの09-testingとmy-testingにfetchした09-testingをマージ(コンフリクト起きたら解消)

2022-12-26 04:47 UTC, u1tnk commented
> 以下の手順で取り込もうと考えているのですが問題ないでしょうか？

はい、その手順で大丈夫です！

2022-12-27 05:41 UTC, doitumura commented on test/models/report_test.rb
> +    assert_equal('2022-01-01'.to_date, @report.created_on)
[ffa178a](https://github.com/doitumura/fjord-books_app/pull/13/commits/ffa178ae6ef44e5a4a13054ab6e3041c9c46a699)で修正しました

2022-12-28 02:18 UTC, doitumura commented on test/models/user_test.rb
> +    assert(@user2.following?(@user1))
[23d3b2c](https://github.com/doitumura/fjord-books_app/pull/13/commits/23d3b2c67de1848748634b0913ff3f64df5610e2)で修正しました。

2022-12-28 02:34 UTC, doitumura commented on test/models/user_test.rb
> +    assert(@user1.followed_by?(@user2))
[d68ed82](https://github.com/doitumura/fjord-books_app/pull/13/commits/d68ed8222c09fd19bedbaa223eee6ab0560a6591)と[c7dd6b8](https://github.com/doitumura/fjord-books_app/pull/13/commits/c7dd6b87181afc3c93509c7b7ada0903d896a1f1)で修正しました。

2022-12-28 02:35 UTC, doitumura commented on test/models/user_test.rb
> +    assert_equal('one@example.com', @user1.name_or_email)
[c7ba529](https://github.com/doitumura/fjord-books_app/pull/13/commits/c7ba5296f5a6a5cfff35ffd6462a0c4aa3276b0d)で修正しました。

2022-12-28 10:02 UTC, u1tnk requested changes

2022-12-29 01:12 UTC, doitumura commented on test/models/user_test.rb
> +    relationship&.save
[f61d8fd](https://github.com/doitumura/fjord-books_app/pull/13/commits/f61d8fdb98e286427a695d5bec82e7f3da7b3169)と[ea73a15](https://github.com/doitumura/fjord-books_app/pull/13/commits/ea73a15ba440afbe334f429421784331acfb215a)で修正しました。

2022-12-29 14:40 UTC, u1tnk approved these changes

2023-04-06 08:54 UTC, merged